version: '3'

services:
  client:
    platform: linux/x86_64
    image: wongsaang/chatgpt-ui-client:latest
    environment:
      - SERVER_DOMAIN=http://web-server
      - DEFAULT_LOCALE=en
    ports:
      - '${CLIENT_PORT:-80}:80'
    networks:
      - chatgpt-ui_network
    restart: always

networks:
  chatgpt-ui_network:
    external: true
